config/routes.rb
Rails.application.routes.draw do
  resources :links
  root :to => "home#index"
  get "posts/index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end


end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end





  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.fetch(:link, {}).permit(:title)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<div class="header">
  <h1>マイ トラブルシューティング<br>
    <h2>どうしても変えたい自分の習慣<br>自分専用の取り扱い説明書の作りかた<br></h2>
  </h1>
</div>

<div class="main">
  <h3>マイ トラブルシューティングとは？</h3>
  <p>自分にとっての変えたい(止めたい)行動を改善するメモツールです。自分だけの取り扱い説明書でもあります。</p>
  <img src="../images/notepen.jpg" alt="note_&amp;_pen" class="note">
  <h3>なぜこれを使った方がいいの？</h3>
  <p>自分の理想像に近づくことができるからです。自分が変えたい(止めたい)と思っている行動より、本当はしたいと思う行動をした方が、理想の自分に近づきやすくなります。<%= link_to "参考にした厚生労働省のサイトです。", "http://www.e-healthnet.mhlw.go.jp/information/exercise/s-07-004.html" %><br>（例：理想の体型になりたいが、お菓子を食べ過ぎてしまう→お菓子を食べる頻度を減らしたい　など）<br>また、メモをしておくことで、何度も同じ対策を考えなくて良くなります。<br>自分に合った方法なので、効果が出やすいです。</p>
  <img src="../images/happyface.jpg" alt="happyface" class="face">
  <h3>どうやってすればいい？</h3>
  <ul>
    <li><p>変えたい行動</p></li>
    <li><p>してしまう状況(原因)</p></li>
    <li><p>その時の対策</p></li>
  </ul>
  <p>をメモしておいて<br>
    変えたい行動をしてしまう時にそのメモを見て
    対策を実行します。<br>
    また、日々の生活の中で気づいた新たな対策を、そのメモに追加していきます。<br><br>
    (例：お菓子を食べる量を減らしたい→家にいて疲れを取りたいと思った時→食べる代わりに5分間目をつぶってリラックスする)
  </p>

  <h3>最後に</h3>
  <p>少しづつメモを増やして実行していき、自分が思い描く、素敵な自分に近づいていきましょう。</p>
  <img src="../images/seikou_banzai_woman.png" alt="banzai_woman" class="woman">


  <div id="form">
    <p></p>
    <p class="form-title">Login</p>
    <form action="post">
      <p>Email</p>
      <p class="mail"><input type="email" name="mail" /></p>
      <p>Password</p>
      <p class="pass"><input type="password" name="pass" /></p>
      <p class="check"><input type="checkbox" name="checkbox" />パスワードを保存</p>
      <p class="submit"><input type="submit" value="Login" /></p>
    </form>
  </div>
</div>
<div>
  <h4>参考URL</h4>
  <%#= link_to "健康行動について(厚生労働省のサイト)",  %>
  <a href="https://www.e-healthnet.mhlw.go.jp/information/exercise/s-07-004.html" target="_blank"></a><br>
  <a href="https://www.e-healthnet.mhlw.go.jp/information/exercise/s-07-003.html" target="_blank">健康行動を高める要因(厚生労働省のサイト)</a><br>
  <a href="https://www.mhlw.go.jp/shingi/2006/08/dl/s0804-7i.pdf" target="_blank">行動変容について(厚生労働省)</a><br>
</div>

app/views/home/record.html.erb
<div class="header">
  <h1>マイ トラブルシューティング<br>
    <h2>どうしても変えたい自分の習慣<br>
      自分専用の取り扱い説明書の作りかた<br></h2>
    </h1>
  </div>
  <!-- <form action=""> -->
  <div class="item">
    <label class="label" for="goal" name="goal">最終目標</label><label class="example">(例)夏までに2kg痩せる！
    </label><br>
    <input id="goal" type="text"><br>
    <%= form_tag("records/create")do %>
    <textarea></textarea>
    <input type="submit" value="編集">
    <% end %>
  </div>
  <div class="item">
    <label class="label" for="month" name="month_goal">今月の目標</label><label class="example">(例)テキスト
    </label><br>
    <input id="month" type="text"><br>
    <input id="month" type="text"><br>
    <input id="month" type="text"><br>
  </div><br>
  <div class="item">
    <label class="label" for="manual" name="goal">自分専用の対策</label><label class="example">(例)テキスト
    </label><br>
    <input id="manual" type="my_manual"><br>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.text_field :title %><br>
    <%= form.submit %>
  </div>
<>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link_to link.title, link %></td>
        <td><%= link_to '編集', edit_link_path(link) %></td>
        <td><%= link_to '×', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

    <% @links.each do |link| %>
      <tr>
        <td><%= link_to "" %></td>
      </tr>
    <% end %>
  </tbody>


</table>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link_to link.title, link %></td>
        <td><%= link_to '編集', edit_link_path(link) %></td>
        <td><%= link_to '×', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

    <% @links.each do |link| %>
      <tr>
        <td><%= link_to "" %></td>
      </tr>
    <% end %>
  </tbody>


</table>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td rowspan="2"><%= link_to link.title, link %></td>
        <td rowspan="2"><%= link_to '編', edit_link_path(link) %></td>
        <td rowspan="2"><%= link_to '×', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% 31.times do |t| %>
          <td><%= t + 1 %></td>
        <% end %>
      </tr>
      <tr>
        <%# 31.times do |t|
          <td>
            link.day[t]
            <%# case num %>
            <%# <% when 0 %>
              <%#= flag %>
            <%# when 1 %>
              <%#= "○" %>
            <%# when 2 %>
              <%#= "△" %>
            <%# when 3 %>
              <%#= "×" %>
            <%# end %>
          </td>
        <%# end %>
      </tr>
    <% end %>

    <% @links.each do |link| %>
      <tr>
        <td><%= link_to "" %></td>
      </tr>
    <% end %>
  </tbody>


</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<%# <%= render 'form', link: @link %> %>
<%= @link.title %>
<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>